export const SET_DATA_REQUEST = "SET_DATA_REQUEST";
export const SET_DATA_SUCCESS = "SET_DATA_SUCCESS";
export const SET_DATA_FAIL = "SET_DATA_FAIL";

export const SET_FILTERED_DATA_REQUEST = "SET_FILTERED_DATA_REQUEST";
export const SET_FILTERED_DATA_SUCCESS = "SET_FILTERED_DATA_SUCCESS";
export const SET_FILTERED_DATA_FAIL = "SET_FILTERED_DATA_FAIL";
